### PR TITLE
Unstable

### PR DESCRIPTION
**Pull request by starryboi**

### CODE REVIEW

**Comment by PaulSonOfLars** [comment]
Smooth, can I submit a PR for you to fix my name? You're clearly doing a great job at copy pasting the code, maybe you need a hand with the rest.

**Comment by skittles9823** [comment]
@PaulSonOfLars Nice. Kanged skittbot here too.

**Comment by starryboi** [comment]
Sorry, i opened this pull request by mistake btw I've added all credits for your work nd i never cloned this bot for people to use i just made to use in some of my groups. Sorry if i did anything wrong.... Cuz I'm still learning git nd stuffs 😓

**Comment by skittles9823** [comment]
@starryboi lol. I see a single commit of my own in your fork and that's just the one commit of mine from Marie's source.

Definitely some missing authorship over there.

**Comment by starryboi** [comment]
I apologise :v I'll take care of this from next time...

**Comment by starryboi** [comment]
@skittles9823 i amended nd added u in your commit its ok now?

**Comment by skittles9823** [comment]
@starryboi there is no way you'd be able to fix credits in your source easily. You've copy pasted code from other projects without even matching where the code was in the other project.

One commit of mine touching up the kang sticker command... Lol.

The original kang command is from @ATechnoHazard which I later improved with the help of deletescape and gotenksIN.

Honestly picking the kang command from skittbot would be impossible, picking from NotAMemeBot would be far easier though. The commits are easier to find there.

**Pull request closed without merging**
