### PR TITLE
Developer verification (Captcha)

### PR DESCRIPTION
**Pull request by deletescape**
This allows us to verify that the person trying to start the bot actually has some basic python knowledge. The puzzle is fairly easy and should be solvable in less than 5 minutes.

> This verification method also accounts for heroku support, by not actually checking the captcha there

I can give you a sample solution of the captcha in private or you can try to figure it out yourself 😉

### CODE REVIEW

**Comment by PaulSonOfLars** [comment]
Love it hahaha

**Comment by keessonnema** [comment]
This is great! I love the idea.

**Comment by krypticallusion** [comment]
@keessonnema lil

**Comment by PaulSonOfLars** [comment]
On further thought, the aim of the project isnt to restrict people from using the code, so this wont be merged.

**Pull request closed without merging**
