### PR TITLE
Update locks.py with pluralized locktypes

### PR DESCRIPTION
**Pull request by AyamDobhal**

### CODE REVIEW

**Comment by songotenks69** [comment]
The inconsistency in plurals has triggered me for a while now

**Comment by AyamDobhal** [comment]
> If you could find a way to make this non-breaking (eg, support both cases) I'll merge this in

alright I'll try

**Comment by PaulSonOfLars** [comment]
Well now you've just broken the /locktypes command

**Comment by AyamDobhal** [comment]
Ah wait. Can you just revert it while I look for another fix?

**Comment by AyamDobhal** [comment]
> How is this looking?

I didn't have time. Been busy

**Pull request closed without merging**
