### PR TITLE
ctrlbot

### PR DESCRIPTION
**Pull request by AVATARX0TIC**
Please accept it

### CODE REVIEW

**Comment by skittles9823** [comment]
@AVATARX0TIC Lmao

**Comment by merothh** [comment]
F

**Comment by PaulSonOfLars** [comment]
What? No, I'm not going to merge you random bot trash into the Marie repository.

And your "made with love by" change is frankly offensive, you've done absolutely sod all to make this bot, you deserve no credit for it

**Comment by PaulSonOfLars** [comment]
Also, there's a reason I put the config.py in the gitignore.

You've leaked your bot token.

**Comment by AVATARX0TIC** [comment]
> Also, there's a reason I put the config.py in the gitignore.
> 
> You've leaked your bot token.

Ohh thanks I will revoke it now

**Comment by Bluscream** [comment]
OwO

**Comment by TsunayoshiSawada** [comment]
That explains why life is tough for Paul.

**Comment by Bluscream** [comment]
It could happen to anyone tho

**Comment by peaktogoo** [comment]
now he edited

**Pull request closed without merging**
