### PR TITLE
Add Wiki

### PR DESCRIPTION
**Pull request by DragSama**
Can you add Wikipedia module to Saitama? As you already have ud having wiki wouldn't hurt :D

### CODE REVIEW

**Comment by MSF-Jarvis** [comment]
Umm w0t

**Comment by akhilnarang** [comment]
@DragSama This is Marie not saitama(?)

**Comment by akhilnarang** [comment]
@DragSama

**Comment by PaulSonOfLars** [comment]
Wrong fork. This isnt the saitama repo, this is Marie.
And this is out of scope of marie's goals.

**Comment by akhilnarang** [comment]
@akhilnarang Rip

**Comment by DragSama** [comment]
Sorry about that 😅

**Pull request closed without merging**
