### PR TITLE
One click installation on Heroku for n00bs

### PR DESCRIPTION
**Pull request by SpEcHiDe**
did the required changes as mentioned [here](https://devcenter.heroku.com/articles/heroku-button#testing-the-app-json-file).

### CODE REVIEW

**Comment by SpEcHiDe** [comment]
What I meant was once this is merged, you will get a button as shown in the image.

image

You can test it out by clicking on this [link](https://heroku.com/deploy?template=https://github.com/sudoshell/tgbot), which will redirect to a page as shown in the below image.

image

**Comment by PaulSonOfLars** [comment]
And the button you set in the readme is different from the one you put here because.. why?

**Comment by SpEcHiDe** [comment]
According to [this](https://devcenter.heroku.com/articles/heroku-button#adding-the-heroku-button), ```There are two ways of referencing the template source code repository:``` 

I thought the implicit way would be good enough. (which automatically detects the current_repository)

**Comment by PaulSonOfLars** [comment]
@ATechnoHazard fantastic question

**Comment by SpEcHiDe** [comment]
Who is set as SUDO? Where?

**Pull request closed without merging**
