### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by freak1151**

### CODE REVIEW

**Comment by msfjarvis** [comment]
Take a moment and reconsider your decision to fork this bot based on your inability to use a platform as simple as GitHub.

**Comment by Surge1223** [comment]
Lmao

**Comment by freak1151** [comment]
msfjarvis sorry sir but i can fork this bot

**Comment by architdate** [comment]
Bruh, why would you make this pull request?

**Comment by Bluscream** [comment]
Lmao

**Comment by Bluscream** [comment]
Good thing tose is closed-src

**Pull request closed without merging**
